### ISSUE TITLE
Unable to login to PI-Hole, got a HTTP status code response '200' instead of '302'

### ISSUE THREAD

**Issue by mhamzahkhan** [eko/pihole-exporter#14] opened 2019-09-27 11:22 UTC
I'm running Pi Hole v4.3.2, and pihole-exporter 0.0.4 from docker hub (ekofr/pihole-exporter:0.0.4).

I have a password set for pihole. 

2019/09/27 11:21:39 ------------------------------------
2019/09/27 11:21:39 -  PI-Hole exporter configuration  -
2019/09/27 11:21:39 ------------------------------------
2019/09/27 11:21:39 PIHoleHostname : pihole.hidden
2019/09/27 11:21:39 PIHolePassword : supersecurepassword
2019/09/27 11:21:39 Port : 9617
2019/09/27 11:21:39 Interval : 30s
2019/09/27 11:21:39 ------------------------------------
2019/09/27 11:21:39 New Prometheus metric registered: domains_blocked
2019/09/27 11:21:39 New Prometheus metric registered: dns_queries_today
2019/09/27 11:21:39 New Prometheus metric registered: ads_blocked_today
2019/09/27 11:21:39 New Prometheus metric registered: ads_percentag_today
2019/09/27 11:21:39 New Prometheus metric registered: unique_domains
2019/09/27 11:21:39 New Prometheus metric registered: queries_forwarded
2019/09/27 11:21:39 New Prometheus metric registered: queries_cached
2019/09/27 11:21:39 New Prometheus metric registered: clients_ever_seen
2019/09/27 11:21:39 New Prometheus metric registered: unique_clients
2019/09/27 11:21:39 New Prometheus metric registered: dns_queries_all_types
2019/09/27 11:21:39 New Prometheus metric registered: reply
2019/09/27 11:21:39 New Prometheus metric registered: top_queries
2019/09/27 11:21:39 New Prometheus metric registered: top_ads
2019/09/27 11:21:39 New Prometheus metric registered: top_sources
2019/09/27 11:21:39 New Prometheus metric registered: forward_destinations
2019/09/27 11:21:39 New Prometheus metric registered: querytypes
2019/09/27 11:21:39 New Prometheus metric registered: status
2019/09/27 11:21:39 Starting HTTP server
2019/09/27 11:22:09 Unable to login to PI-Hole, got a HTTP status code response '200' instead of '302'

**Comment by eko** [comment] 2019-09-29 13:45
Hi @mhamzahkhan,

Thank you for reporting this issue, indeed PI-Hole has changed the login response status code on their API so I have to deal with it.

I just upgraded my own PI-Hole too and I can confirm the issue is fixed ;)

This is now fixed in new 0.0.5 release, you can grab the new binary here: https://github.com/eko/pihole-exporter/releases/tag/0.0.5

Thank you!

**Closed by eko** 2019-09-29 13:45 UTC
