### ISSUE TITLE
Exporter isn't showing any data

### ISSUE THREAD

**Issue by kbreit** [eko/pihole-exporter#7] opened 2019-06-01 03:55 UTC
I setup the exporter as a Docker container and Prometheus is showing the target as up. However, when I click the target metrics page, I see 0's for everything. 

`pihole_status{hostname="192.168.15.15"} 0`

Pihole is indeed up. I've used both the API key and the password in the exporter and the result is the same.

**Comment by eko** [comment] 2019-06-06 20:38
Hi @kbreit,

I think I can close this now since you've added the hostname on Grafana dashboard? This is not really related to the Prometheus exporter ;)

**Comment by kbreit** [comment] 2019-06-07 02:50
When I look at the metrics page for the exporter, almost all the values are 0. I can’t tell if it’s communicating with pihole or not.

**Comment by eko** [comment] 2019-06-09 16:32
Have you tried with the dashboard on this repository that allows you to select the node?

See: https://github.com/eko/pihole-exporter/blob/master/grafana/dashboard.json

**Comment by pellett22** [comment] 2019-06-10 13:39
same issue here.  Appears there are no Prometheus queries in the dashboard that was downloaded from this repository

**Comment by kbreit** [comment] 2019-06-10 13:56
That's what I'm seeing. When I go to the `/metrics` page, all the metrics are 0. I used the Grafana explorer, and Prometheus, to test this and getting the same result.

**Comment by pellett22** [comment] 2019-06-10 14:15
I believe the issue is that the datasource for influxdb is called 'pihole' too.

When I removed the influxdb datasource, the dashboard starting displaying data.

**Comment by eko** [comment] 2019-06-12 18:01
Do you have precized the correct IP address of you PI-Hoke instance when running the exporter? (see Readme file)

**Comment by kbreit** [comment] 2019-06-13 02:24
The correct IP address is in my configuration. I did run a `docker logs pihole-exporter` and did see a ton of these errors. Are they consequential?

`2019/06/13 02:20:12 Unable to unmarshal PI-Hole statistics to statistics struct model invalid character '<' looking for beginning of value`

**Comment by eko** [comment] 2019-06-14 17:58
@kbreit,

Are you able to look at the API stats on the PI-Hole API URL: http://<IP of your PI-Hole>/admin/api.php?summaryRaw&overTimeData&topItems&recentItems&getQueryTypes&getForwardDestinations&getQuerySources&jsonForceObject

In case you have a password on your instance, please ensure that you provide the right password on `pihole_password` config option (see: https://github.com/eko/pihole-exporter#available-cli-options).

**Comment by d7eeem** [comment] 2019-06-28 15:18
main is this 
Annotation Query Failed
Datasource named ${DS_PROMETHEUS1} was not found

**Comment by eko** [comment] 2020-02-01 16:38
Closing this issue as it's too old and I cannot find any trace of `DS_PROMETHEUS1` variable anywhere in Grafana dashboard or in this repository.

I hope this is fixed for you now. Thank you

**Closed** 2020-02-01 16:38 UTC
