### ISSUE TITLE
Docker deployment - memory leak

### ISSUE THREAD

**Issue by joachimnielandt** [eko/pihole-exporter#54] opened 2020-07-02 17:27 UTC
I noticed a memory consumption of 1.3GB for piholeexporter last I checked my monitoring. After restarting, that dropped to 20MB, which promply started climbing steadily again. In 3 hours it went from 29MB to 37MB. I guess there's a memory leak?

I'm using the following docker-compose setup (pulled and checked that the latest also had the behaviour):
```
  piholeexporter:
    container_name: piholeexporter
    image: ekofr/pihole-exporter:latest
    depends_on:
      - pihole
    restart: unless-stopped
    environment:
      PIHOLE_HOSTNAME: 'x'
      PIHOLE_PASSWORD: 'x'
      INTERVAL: '30s'
      PORT: '9617'
```

**Comment by eko** [comment] 2021-01-01 19:35
Thank you, I will take a look at this. Closing because it is a duplicate of https://github.com/eko/pihole-exporter/issues/45

**Closed by eko** 2021-01-01 19:35 UTC
